@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>About</h2>
            <div class="bg-black">
                <p>CheckCD.rip is a tool for verifying and scoring log files generated by Exact Audio Copy. This
                    website makes use of <a href="https://github.com/DenzoNL/riplogchecker" target="_blank">riplogchecker</a>
                    in order to parse and score logs. In the future, an API will also be provided.
                </p>
                <h3>Your privacy</h3>
                <p>CheckCD.rip does not collect any data of any kind on its user, nor are submitted logs stored on the
                    server. The logs are only
                    parsed and results are returned.</p>
                <h3>Troubleshooting</h3>
                <p>
                    CheckCD.rip does not make any guarantees for the functioning of the tool. However, we are determined
                    to provide the best and most accurate log checker available, so if you do find an issue or error
                    with a log that you submitted, we ask you to create a new issue on <a
                            href="https://github.com/DenzoNL/riplogchecker/issues/new" target="_blank">the riplogchecker GitHub
                        page</a> so that in the future the issue may be resolved.
                </p>
            </div>
        </div>
    </div>
</div>
@endsection