<!DOCTYPE html>
<html class="full" lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>CheckCD.rip</title>

    <!-- App CSS -->
    <link href="css/app.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url('/') }}"><strong>CheckCD</strong>.rip</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href="{{ url('/about') }}">About</a>
                </li>
                <li>
                    <a href="https://github.com/DenzoNL/riplogchecker" target="_blank">GitHub</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>About</h2>
            <div class="bg-black">
                <p>CheckCD.rip is a tool for verifying and scoring log files generated by Exact Audio Copy. This
                    website makes use of <a href="https://github.com/DenzoNL/riplogchecker" target="_blank">riplogchecker</a>
                    in order to parse and score logs. In the future, an API will also be provided.
                </p>
                <h3>Your privacy</h3>
                <p>CheckCD.rip does not collect any data of any kind on its user, nor are submitted logs stored on the
                    server. The logs are only
                    parsed and results are returned.</p>
                <h3>Troubleshooting</h3>
                <p>
                    CheckCD.rip does not make any guarantees for the functioning of the tool. However, we are determined
                    to provide the best and most accurate log checker available, so if you do find an issue or error
                    with a log that you submitted, we ask you to create a new issue on <a
                            href="https://github.com/DenzoNL/riplogchecker/issues/new" target="_blank">the riplogchecker GitHub
                        page</a> so that in the future the issue may be resolved.
                </p>
            </div>
        </div>
    </div>
</div>
<!-- Put your page content here! -->

<!-- App JS -->
<script src="js/app.js"></script>

</body>

</html>